import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import cors from '@fastify/cors';
import rateLimit from '@fastify/rate-limit';
import crypto from 'node:crypto';
import { query, tx } from './db';
import { hashToken, password, publicId, randomToken } from './security';
import * as ptero from './ptero';

const app=Fastify({logger:true,trustProxy:true});
const DASH=process.env.DASHBOARD_URL || 'https://dash.atxcloud.ggff.net';
const COOKIE=process.env.ATXCLOUD_COOKIE_SECRET || '';
const prefixes=['Stone','Dirt','Creeper','Quartz','Obsidian','Ruby','Iron','Oak','Ash','Nova'];

await app.register(cookie,{secret:COOKIE});
await app.register(cors,{origin:DASH,credentials:true});
await app.register(rateLimit,{max:120, timeWindow:'1 minute'});

async function discordToken(code:string){ const r=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID!,client_secret:process.env.DISCORD_CLIENT_SECRET!,grant_type:'authorization_code',code,redirect_uri:process.env.DISCORD_REDIRECT_URI!})}); if(!r.ok) throw new Error('Discord OAuth exchange failed'); return r.json() as Promise<any>; }
async function discordMe(token:string){ const r=await fetch('https://discord.com/api/users/@me',{headers:{Authorization:`Bearer ${token}`}}); if(!r.ok) throw new Error('Discord identity failed'); return r.json() as Promise<any>; }
async function discordMember(id:string){ if(!process.env.DISCORD_BOT_TOKEN||!process.env.DISCORD_GUILD_ID)return null; const r=await fetch(`https://discord.com/api/guilds/${process.env.DISCORD_GUILD_ID}/members/${id}`,{headers:{Authorization:`Bot ${process.env.DISCORD_BOT_TOKEN}`}}); return r.ok?r.json() as Promise<any>:null; }
async function isStaff(id:string){ const m=await discordMember(id); const roles=(process.env.STAFF_ROLE_IDS||'').split(',').map(x=>x.trim()).filter(Boolean); return !!m && roles.some(x=>m.roles?.includes(x)); }

async function auth(req:any,res:any){ const raw=req.cookies.atx_session; if(!raw) return null; const s=await query<any>('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now() AND u.blacklisted=false',[hashToken(raw)]); if(!s.rows[0]){res.clearCookie('atx_session',{path:'/'});return null;} return s.rows[0]; }
function requireUser(req:any,res:any){ return auth(req,res); }
function err(e:any){ const status=e?.response?.status; const data=e?.response?.data; return {status:status && status>=400 && status<600?status:500,message:data?.errors?.[0]?.detail||e?.message||'Operation failed'}; }
async function audit(actor:any,action:string,targetType?:string,targetId?:string,metadata:any={}){ await query('INSERT INTO audit_logs(actor_user_id,actor_discord_id,action,target_type,target_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[actor?.id||null,actor?.discord_id||null,action,targetType||null,targetId||null,metadata]); }
async function uniquePublicId(){ for(let i=0;i<30;i++){const id=publicId(prefixes[crypto.randomInt(prefixes.length)]); const r=await query('SELECT 1 FROM servers WHERE public_id=$1',[id]); if(!r.rowCount)return id;} throw new Error('Could not allocate public server ID'); }

app.get('/health',async()=>({ok:true,service:'api',time:new Date().toISOString()}));
app.get('/auth/discord',async(_req,res)=>{ const state=randomToken(24); res.setCookie('oauth_state',state,{httpOnly:true,secure:true,sameSite:'lax',maxAge:600,path:'/'}); const u=new URL('https://discord.com/oauth2/authorize'); u.searchParams.set('client_id',process.env.DISCORD_CLIENT_ID!);u.searchParams.set('redirect_uri',process.env.DISCORD_REDIRECT_URI!);u.searchParams.set('response_type','code');u.searchParams.set('scope','identify email'); return res.redirect(u.toString()); });
app.get('/auth/discord/callback',async(req:any,res)=>{ try{if(!req.cookies.oauth_state||req.query.state!==req.cookies.oauth_state)throw new Error('Invalid OAuth state'); const t=await discordToken(req.query.code);const d=await discordMe(t.access_token); const u=await tx(async(c)=>{const q=await c.query<any>('INSERT INTO users(discord_id,username,email) VALUES($1,$2,$3) ON CONFLICT(discord_id) DO UPDATE SET username=EXCLUDED.username,email=COALESCE(EXCLUDED.email,users.email),updated_at=now() RETURNING *',[d.id,d.username,d.email||null]);return q.rows[0];}); const raw=randomToken(48); await query('INSERT INTO sessions(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval \'14 days\')',[u.id,hashToken(raw)]); res.clearCookie('oauth_state',{path:'/'});res.setCookie('atx_session',raw,{httpOnly:true,secure:true,sameSite:'lax',maxAge:1209600,path:'/'}); return res.redirect(`${DASH}/dashboard`);}catch(e){req.log.error(e);return res.redirect(`${DASH}/login?error=oauth_failed`);} });
app.post('/auth/logout',async(req:any,res)=>{const raw=req.cookies.atx_session;if(raw)await query('DELETE FROM sessions WHERE token_hash=$1',[hashToken(raw)]);res.clearCookie('atx_session',{path:'/'});return {ok:true};});
app.get('/me',async(req,res)=>{const u=await auth(req,res);if(!u)return res.code(401).send({error:'unauthorized'});const servers=await query('SELECT s.public_id,s.name,s.category,s.version,s.suspended,s.created_at,n.name node FROM servers s LEFT JOIN nodes n ON n.id=s.node_id WHERE s.owner_id=$1 AND s.deleted_at IS NULL ORDER BY s.created_at DESC',[u.id]);return {user:{id:u.id,discordId:u.discord_id,username:u.username,email:u.email,coins:u.coins,blacklisted:u.blacklisted,createdAt:u.created_at},servers:servers.rows,staff:await isStaff(u.discord_id)};});
app.get('/servers',async(req,res)=>{const u=await requireUser(req,res);if(!u)return res.code(401).send({error:'unauthorized'});const q=await query<any>(`SELECT s.*,n.name node_name FROM servers s LEFT JOIN nodes n ON n.id=s.node_id WHERE s.deleted_at IS NULL AND (s.owner_id=$1 OR EXISTS(SELECT 1 FROM server_access a WHERE a.server_id=s.id AND a.user_id=$1)) ORDER BY s.created_at DESC`,[u.id]);return q.rows;});
app.get('/servers/:id',async(req:any,res)=>{const u=await requireUser(req,res);if(!u)return res.code(401).send({error:'unauthorized'});const q=await query<any>(`SELECT s.*,n.name node_name FROM servers s LEFT JOIN nodes n ON n.id=s.node_id WHERE s.public_id=$1 AND s.deleted_at IS NULL AND (s.owner_id=$2 OR EXISTS(SELECT 1 FROM server_access a WHERE a.server_id=s.id AND a.user_id=$2))`,[req.params.id,u.id]);if(!q.rows[0])return res.code(404).send({error:'server_not_found'});let resource=null;try{if(q.rows[0].ptero_identifier&&process.env.PTERODACTYL_CLIENT_KEY)resource=await ptero.resources(q.rows[0].ptero_identifier,process.env.PTERODACTYL_CLIENT_KEY);}catch{}return {server:q.rows[0],resource};});
app.post('/servers/:id/power',async(req:any,res)=>{const u=await requireUser(req,res);if(!u)return res.code(401).send({error:'unauthorized'});const signal=req.body?.signal;if(!['start','stop','restart','kill'].includes(signal))return res.code(400).send({error:'invalid_signal'});const q=await query<any>(`SELECT s.* FROM servers s WHERE s.public_id=$1 AND s.deleted_at IS NULL AND (s.owner_id=$2 OR EXISTS(SELECT 1 FROM server_access a WHERE a.server_id=s.id AND a.user_id=$2))`,[req.params.id,u.id]);if(!q.rows[0])return res.code(404).send({error:'server_not_found'});if(q.rows[0].suspended)return res.code(409).send({error:'server_suspended'});if(!process.env.PTERODACTYL_CLIENT_KEY)return res.code(503).send({error:'pterodactyl_client_key_not_configured'});try{await ptero.power(q.rows[0].ptero_identifier,process.env.PTERODACTYL_CLIENT_KEY,signal);await audit(u,`server.${signal}`,'server',q.rows[0].public_id);return {ok:true};}catch(e){const x=err(e);return res.code(x.status).send({error:x.message});}});

app.post('/servers',async(req:any,res)=>{const u=await requireUser(req,res);if(!u)return res.code(401).send({error:'unauthorized'});if(u.blacklisted)return res.code(403).send({error:'blacklisted'});const b=req.body||{};if(!b.name||!Number.isInteger(b.nodeId)||!Number.isInteger(b.eggId)||!Number.isInteger(b.nestId))return res.code(400).send({error:'name,nodeId,nestId,eggId_required'});const existing=await query('SELECT 1 FROM servers WHERE owner_id=$1 AND deleted_at IS NULL',[u.id]);if(existing.rowCount)return res.code(409).send({error:'server_limit_reached'});const node=await query<any>('SELECT n.*,p.enabled policy_enabled FROM nodes n LEFT JOIN node_policies p ON p.node_id=n.id AND p.nest_id=$2 AND p.egg_id=$3 WHERE n.id=$1',[b.nodeId,b.nestId,b.eggId]);if(!node.rows[0]||!node.rows[0].enabled||node.rows[0].policy_enabled===false)return res.code(409).send({error:'node_policy_denied'});if(!u.ptero_user_id)return res.code(409).send({error:'pterodactyl_account_missing'});if(!process.env.PTERODACTYL_APPLICATION_KEY)return res.code(503).send({error:'pterodactyl_application_key_not_configured'});const pub=await uniquePublicId();try{const created=await ptero.createServer({name:b.name,user:u.ptero_user_id,egg:b.eggId,docker_image:b.dockerImage||'ghcr.io/pterodactyl/yolks:java_21',startup:b.startup||'java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}}',environment:b.environment||{},limits:{memory:1024,swap:0,disk:5120,io:500,cpu:70},feature_limits:{databases:0,backups:3,allocations:1},deploy:{locations:[node.rows[0].ptero_node_id],dedicated_ip:false,port_range:[]},start_on_completion:false});const row=await query<any>('INSERT INTO servers(public_id,ptero_server_id,ptero_identifier,owner_id,node_id,name,category,nest_id,egg_id,version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[pub,created.id,created.identifier,u.id,b.nodeId,b.name,b.category||'code',b.nestId,b.eggId,b.version||null]);await audit(u,'server.create','server',pub);return res.code(201).send(row.rows[0]);}catch(e){const x=err(e);return res.code(x.status).send({error:x.message});}});

app.post('/coins/gift',async(req:any,res)=>{const u=await requireUser(req,res);if(!u)return res.code(401).send({error:'unauthorized'});const target=await query<any>('SELECT * FROM users WHERE discord_id=$1 AND blacklisted=false',[req.body?.discordId]);const amount=Number(req.body?.coins);if(!target.rows[0])return res.code(404).send({error:'target_account_not_found'});if(!Number.isSafeInteger(amount)||amount<=0)return res.code(400).send({error:'invalid_amount'});if(target.rows[0].id===u.id)return res.code(400).send({error:'self_transfer'});const key=String(req.body?.idempotencyKey||'');if(!key)return res.code(400).send({error:'idempotency_key_required'});try{await tx(async(c)=>{const prior=await c.query('SELECT 1 FROM coin_ledger WHERE idempotency_key=$1',[key]);if(prior.rowCount)return;const a=await c.query<any>('SELECT coins FROM users WHERE id=$1 FOR UPDATE',[u.id]);if(Number(a.rows[0].coins)<amount)throw Object.assign(new Error('insufficient_coins'),{statusCode:409});await c.query('UPDATE users SET coins=coins-$1,updated_at=now() WHERE id=$2',[amount,u.id]);await c.query('UPDATE users SET coins=coins+$1,updated_at=now() WHERE id=$2',[amount,target.rows[0].id]);await c.query('INSERT INTO coin_ledger(idempotency_key,user_id,actor_id,amount,type,reference) VALUES($1,$2,$3,$4,$5,$6)',[key,u.id,u.id,-amount,'gift',target.rows[0].discord_id]);await c.query('INSERT INTO coin_ledger(idempotency_key,user_id,actor_id,amount,type,reference) VALUES($1,$2,$3,$4,$5,$6)',[`${key}:receiver`,target.rows[0].id,u.id,amount,'gift',u.discord_id]);});await audit(u,'coins.gift','user',target.rows[0].id,{amount});return {ok:true};}catch(e:any){return res.code(e.statusCode||500).send({error:e.message||'transfer_failed'});}});

async function accessChange(req:any,res:any,remove:boolean){const u=await requireUser(req,res);if(!u)return res.code(401).send({error:'unauthorized'});const q=await query<any>('SELECT s.* FROM servers s WHERE s.public_id=$1 AND s.owner_id=$2 AND s.deleted_at IS NULL',[req.body?.serverId,u.id]);if(!q.rows[0])return res.code(403).send({error:'owner_required'});const target=await query<any>('SELECT id FROM users WHERE discord_id=$1 AND blacklisted=false',[req.body?.discordId]);if(!target.rows[0])return res.code(404).send({error:'target_account_not_found'});if(remove)await query('DELETE FROM server_access WHERE server_id=$1 AND user_id=$2',[q.rows[0].id,target.rows[0].id]);else await query('INSERT INTO server_access(server_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[q.rows[0].id,target.rows[0].id]);await audit(u,remove?'server.access.remove':'server.access.add','server',q.rows[0].public_id,{target:target.rows[0].id});return {ok:true};}
app.post('/servers/access/add',(req,res)=>accessChange(req,res,false));app.post('/servers/access/remove',(req,res)=>accessChange(req,res,true));

app.get('/staff/stats',async(req,res)=>{const u=await requireUser(req,res);if(!u)return res.code(401).send({error:'unauthorized'});if(!await isStaff(u.discord_id))return res.code(403).send({error:'staff_required'});const [users,black,mc,code,running,suspended]=await Promise.all([query('SELECT count(*)::int n FROM users'),query('SELECT count(*)::int n FROM users WHERE blacklisted'),query("SELECT count(*)::int n FROM servers WHERE category='minecraft' AND deleted_at IS NULL"),query("SELECT count(*)::int n FROM servers WHERE category='code' AND deleted_at IS NULL"),query("SELECT count(*)::int n FROM servers WHERE deleted_at IS NULL AND suspended=false"),query("SELECT count(*)::int n FROM servers WHERE deleted_at IS NULL AND suspended=true")]);return {users:users.rows[0].n,blacklisted:black.rows[0].n,minecraftServers:mc.rows[0].n,codeServers:code.rows[0].n,running:running.rows[0].n,suspended:suspended.rows[0].n};});

app.setErrorHandler((e,req,res)=>{req.log.error(e);return res.code((e as any).statusCode||500).send({error:e.message||'internal_error'});});
app.listen({host:'0.0.0.0',port:Number(process.env.PORT||4000)}).catch(e=>{app.log.error(e);process.exit(1);});
