import {FastifyInstance} from 'fastify';
import {query} from './db';
import * as ptero from './ptero';
import {timingEqual} from './security';
async function staffActor(req:any){const secret=String(req.headers['x-atx-internal-secret']||'');if(!timingEqual(secret,process.env.ATXCLOUD_INTERNAL_SECRET||''))return null;const id=String(req.headers['x-discord-user']||'');const u=(await query<any>('SELECT * FROM users WHERE discord_id=$1 AND blacklisted=false',[id])).rows[0];if(!u)return null;const m=await fetch(`https://discord.com/api/guilds/${process.env.DISCORD_GUILD_ID}/members/${id}`,{headers:{Authorization:`Bot ${process.env.DISCORD_BOT_TOKEN}`}});if(!m.ok)return null;const member:any=await m.json();const roles=(process.env.STAFF_ROLE_IDS||'').split(',').map(x=>x.trim()).filter(Boolean);return roles.some(x=>member.roles?.includes(x))?u:null;}
export async function registerInternalStaffRoutes(app:FastifyInstance){
 app.get('/internal/staff/accounts',async(req:any,res)=>{if(!await staffActor(req,res))return res.code(403).send({error:'staff_required'});const r=await query<any>('SELECT username,email,discord_id,coins,blacklisted,created_at FROM users ORDER BY created_at DESC');return {accounts:r.rows};});
 app.get('/internal/staff/servers',async(req:any,res)=>{if(!await staffActor(req,res))return res.code(403).send({error:'staff_required'});const r=await query<any>('SELECT s.public_id,s.name,s.category,s.version,s.suspended,u.username owner,n.name node_name FROM servers s JOIN users u ON u.id=s.owner_id LEFT JOIN nodes n ON n.id=s.node_id WHERE s.deleted_at IS NULL ORDER BY s.created_at DESC');return {servers:r.rows};});
 app.get('/internal/staff/stats',async(req:any,res)=>{if(!await staffActor(req,res))return res.code(403).send({error:'staff_required'});const [u,b,s,m,c,r,sp]=await Promise.all([query('SELECT count(*)::int n FROM users'),query('SELECT count(*)::int n FROM users WHERE blacklisted'),query('SELECT count(*)::int n FROM servers WHERE deleted_at IS NULL'),query("SELECT count(*)::int n FROM servers WHERE category='minecraft' AND deleted_at IS NULL"),query("SELECT count(*)::int n FROM servers WHERE category='code' AND deleted_at IS NULL"),query('SELECT count(*)::int n FROM servers WHERE deleted_at IS NULL AND suspended=false'),query('SELECT count(*)::int n FROM servers WHERE deleted_at IS NULL AND suspended=true')]);return {users:u.rows[0].n,blacklisted:b.rows[0].n,totalServers:s.rows[0].n,minecraftServers:m.rows[0].n,codeServers:c.rows[0].n,running:r.rows[0].n,suspended:sp.rows[0].n};});
 app.get('/internal/staff/user/:discordId',async(req:any,res)=>{if(!await staffActor(req,res))return res.code(403).send({error:'staff_required'});const u=await query<any>('SELECT id,username,email,discord_id,coins,blacklisted,created_at FROM users WHERE discord_id=$1',[req.params.discordId]);if(!u.rows[0])return res.code(404).send({error:'user_not_found'});const s=await query<any>('SELECT public_id,name,category,suspended,version FROM servers WHERE owner_id=$1 AND deleted_at IS NULL',[u.rows[0].id]);return {user:u.rows[0],servers:s.rows};});
 app.post('/internal/staff/server/:id/action',async(req:any,res)=>{const actor=await staffActor(req,res);if(!actor)return res.code(403).send({error:'staff_required'});const s=await query<any>('SELECT * FROM servers WHERE public_id=$1 AND deleted_at IS NULL',[req.params.id]);if(!s.rows[0])return res.code(404).send({error:'server_not_found'});const row=s.rows[0],action=String(req.body?.action||'');if(['start','stop','restart','kill'].includes(action)){if(row.suspended)return res.code(409).send({error:'server_suspended'});await ptero.power(row.ptero_identifier,process.env.PTERODACTYL_CLIENT_KEY!,action as any);}else if(action==='suspend'||action==='unsuspend'){const v=action==='suspend';if(v)await ptero.suspendServer(Number(row.ptero_server_id));else await ptero.unsuspendServer(Number(row.ptero_server_id));await query('UPDATE servers SET suspended=$1,updated_at=now() WHERE id=$2',[v,row.id]);}else if(action==='delete'){await ptero.deleteServer(Number(row.ptero_server_id));await query('UPDATE servers SET deleted_at=now(),updated_at=now() WHERE id=$1',[row.id]);}else return res.code(400).send({error:'unsupported_action'});return {ok:true};});
 app.post('/internal/staff/purge',async(req:any,res)=>{const actor=await staffActor(req,res);if(!actor)return res.code(403).send({error:'staff_required'});const mode=String(req.body?.mode||''),node=String(req.body?.node||'all');const args:any[]=[];const w=['s.deleted_at IS NULL'];let n=1;if(node!=='all'){w.push(`pn.id=$${n++}`);args.push(Number(node));}if(mode==='suspended')w.push('s.suspended=true');else if(mode==='offline')w.push('s.suspended=false');else if(mode==='blacklisted')w.push('u.blacklisted=true');else return res.code(400).send({error:'invalid_mode'});const r=await query<any>(`SELECT s.* FROM servers s JOIN users u ON u.id=s.owner_id LEFT JOIN nodes pn ON pn.id=s.node_id WHERE ${w.join(' AND ')}`,args);if(req.body?.confirm!==true)return {confirmRequired:true,count:r.rowCount};let deleted=0,failed=0;for(const s of r.rows){try{await ptero.deleteServer(Number(s.ptero_server_id));await query('UPDATE servers SET deleted_at=now(),updated_at=now() WHERE id=$1',[s.id]);deleted++;}catch{failed++;}}return {ok:true,matched:r.rowCount,deleted,failed};});
}
