import {FastifyInstance} from 'fastify';
import {query,tx} from './db';
import * as ptero from './ptero';
import {timingEqual} from './security';

async function actor(req:any,res:any){
  const secret=String(req.headers['x-atx-internal-secret']||'');
  if(!timingEqual(secret,process.env.ATXCLOUD_INTERNAL_SECRET||''))return null;
  const discordId=String(req.headers['x-discord-user']||'');
  if(!discordId)return null;
  const r=await query<any>('SELECT * FROM users WHERE discord_id=$1',[discordId]);
  if(!r.rows[0]||r.rows[0].blacklisted)return null;
  return r.rows[0];
}
async function serverFor(userId:string,publicId:string){return (await query<any>('SELECT s.*,n.name node_name FROM servers s LEFT JOIN nodes n ON n.id=s.node_id WHERE s.public_id=$1 AND s.deleted_at IS NULL AND (s.owner_id=$2 OR EXISTS(SELECT 1 FROM server_access a WHERE a.server_id=s.id AND a.user_id=$2))',[publicId,userId])).rows[0];}
async function staff(user:any){const r=await fetch(`https://discord.com/api/guilds/${process.env.DISCORD_GUILD_ID}/members/${user.discord_id}`,{headers:{Authorization:`Bot ${process.env.DISCORD_BOT_TOKEN}`}});if(!r.ok)return false;const m:any=await r.json();const roles=(process.env.STAFF_ROLE_IDS||'').split(',').map(x=>x.trim()).filter(Boolean);return roles.some(x=>m.roles?.includes(x));}

export async function registerInternalRoutes(app:FastifyInstance){
 app.get('/internal/me',async(req:any,res)=>{const u=await actor(req,res);if(!u)return res.code(401).send({error:'unauthorized'});const s=await query('SELECT public_id,name,category,version,suspended,created_at,node_id FROM servers WHERE owner_id=$1 AND deleted_at IS NULL ORDER BY created_at DESC',[u.id]);return {user:{id:u.id,discordId:u.discord_id,username:u.username,email:u.email,coins:u.coins,createdAt:u.created_at},servers:s.rows,staff:await staff(u)};});
 app.get('/internal/servers',async(req:any,res)=>{const u=await actor(req,res);if(!u)return res.code(401).send({error:'unauthorized'});const r=await query<any>('SELECT s.*,n.name node_name FROM servers s LEFT JOIN nodes n ON n.id=s.node_id WHERE s.deleted_at IS NULL AND (s.owner_id=$1 OR EXISTS(SELECT 1 FROM server_access a WHERE a.server_id=s.id AND a.user_id=$1)) ORDER BY s.created_at DESC',[u.id]);return r.rows;});
 app.get('/internal/servers/:id',async(req:any,res)=>{const u=await actor(req,res);if(!u)return res.code(401).send({error:'unauthorized'});const s=await serverFor(u.id,req.params.id);if(!s)return res.code(404).send({error:'server_not_found'});let resource=null;try{if(process.env.PTERODACTYL_CLIENT_KEY)resource=await ptero.resources(s.ptero_identifier,process.env.PTERODACTYL_CLIENT_KEY);}catch{}return {server:s,resource};});
 app.post('/internal/servers/:id/power',async(req:any,res)=>{const u=await actor(req,res);if(!u)return res.code(401).send({error:'unauthorized'});const s=await serverFor(u.id,req.params.id);if(!s)return res.code(404).send({error:'server_not_found'});const signal=req.body?.signal;if(!['start','stop','restart','kill'].includes(signal))return res.code(400).send({error:'invalid_signal'});if(s.suspended)return res.code(409).send({error:'server_suspended'});if(!process.env.PTERODACTYL_CLIENT_KEY)return res.code(503).send({error:'client_key_not_configured'});await ptero.power(s.ptero_identifier,process.env.PTERODACTYL_CLIENT_KEY,signal);return {ok:true};});
 app.post('/internal/coins/gift',async(req:any,res)=>{const u=await actor(req,res);if(!u)return res.code(401).send({error:'unauthorized'});const amount=Number(req.body?.coins),target=await query<any>('SELECT id,discord_id,blacklisted FROM users WHERE discord_id=$1',[String(req.body?.targetDiscordId)]);if(!target.rows[0]||target.rows[0].blacklisted)return res.code(404).send({error:'target_account_not_found'});if(!Number.isSafeInteger(amount)||amount<=0)return res.code(400).send({error:'invalid_amount'});if(target.rows[0].id===u.id)return res.code(400).send({error:'self_transfer'});const key=String(req.body?.idempotencyKey||'');if(!key)return res.code(400).send({error:'idempotency_key_required'});await tx(async(c)=>{const prior=await c.query('SELECT 1 FROM coin_ledger WHERE idempotency_key=$1',[key]);if(prior.rowCount)return;const ids=[u.id,target.rows[0].id].sort();const locked=await c.query<any>('SELECT id,coins FROM users WHERE id=ANY($1::uuid[]) FOR UPDATE',[ids]);const sender=locked.rows.find((x:any)=>x.id===u.id);if(Number(sender.coins)<amount)throw Object.assign(new Error('insufficient_coins'),{statusCode:409});await c.query('UPDATE users SET coins=coins-$1,updated_at=now() WHERE id=$2',[amount,u.id]);await c.query('UPDATE users SET coins=coins+$1,updated_at=now() WHERE id=$2',[amount,target.rows[0].id]);await c.query('INSERT INTO coin_ledger(idempotency_key,user_id,actor_id,amount,type,reference) VALUES($1,$2,$3,$4,\'gift\',$5)',[key,u.id,u.id,-amount,target.rows[0].discord_id]);await c.query('INSERT INTO coin_ledger(idempotency_key,user_id,actor_id,amount,type,reference) VALUES($1,$2,$3,$4,\'gift\',$5)',[`${key}:receiver`,target.rows[0].id,u.id,amount,u.discord_id]);});return {ok:true};});
 app.post('/internal/access',async(req:any,res)=>{const u=await actor(req,res);if(!u)return res.code(401).send({error:'unauthorized'});const s=await query<any>('SELECT * FROM servers WHERE public_id=$1 AND owner_id=$2 AND deleted_at IS NULL',[String(req.body?.serverId),u.id]);if(!s.rows[0])return res.code(403).send({error:'owner_required'});const target=await query<any>('SELECT id FROM users WHERE discord_id=$1 AND blacklisted=false',[String(req.body?.targetDiscordId)]);if(!target.rows[0])return res.code(404).send({error:'target_account_not_found'});if(req.body?.action==='remove')await query('DELETE FROM server_access WHERE server_id=$1 AND user_id=$2',[s.rows[0].id,target.rows[0].id]);else if(req.body?.action==='add')await query('INSERT INTO server_access(server_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[s.rows[0].id,target.rows[0].id]);else return res.code(400).send({error:'invalid_action'});return {ok:true};});
 app.get('/internal/staff/check',async(req:any,res)=>{const u=await actor(req,res);if(!u)return res.code(401).send({error:'unauthorized'});return {staff:await staff(u)};});
}
