import {FastifyInstance} from 'fastify';
import {query} from './db';
import * as ptero from './ptero';

async function server(req:any,res:any){
  const u=req.user;
  const r=await query<any>(`SELECT s.* FROM servers s WHERE s.public_id=$1 AND s.deleted_at IS NULL AND (s.owner_id=$2 OR EXISTS(SELECT 1 FROM server_access a WHERE a.server_id=s.id AND a.user_id=$2))`,[String(req.params.id),u.id]);
  return r.rows[0]||null;
}

export async function registerServerControlRoutes(app:FastifyInstance,auth:(req:any,res:any)=>Promise<any>){
  app.addHook('preHandler',async(req:any,res:any)=>{if(!req.url.startsWith('/control/'))return;const u=await auth(req,res);if(!u)return res.code(401).send({error:'unauthorized'});req.user=u;if(u.blacklisted)return res.code(403).send({error:'blacklisted'});});
  const key=()=>process.env.PTERODACTYL_CLIENT_KEY||'';
  app.get('/control/servers/:id/files',async(req:any,res:any)=>{const s=await server(req,res);if(!s)return res.code(404).send({error:'server_not_found'});try{return {directory:String(req.query?.directory||'/'),files:await ptero.listFiles(s.ptero_identifier,key(),String(req.query?.directory||'/'))};}catch(e){const z=ptero.pteroError(e);return res.code(z.statusCode).send({error:z.message});}});
  app.get('/control/servers/:id/file',async(req:any,res:any)=>{const s=await server(req,res);if(!s)return res.code(404).send({error:'server_not_found'});const file=String(req.query?.path||'');if(!file.startsWith('/'))return res.code(400).send({error:'absolute_path_required'});try{return {path:file,content:await ptero.getFile(s.ptero_identifier,key(),file)};}catch(e){const z=ptero.pteroError(e);return res.code(z.statusCode).send({error:z.message});}});
  app.put('/control/servers/:id/file',async(req:any,res:any)=>{const s=await server(req,res);if(!s)return res.code(404).send({error:'server_not_found'});const file=String(req.body?.path||'');if(!file.startsWith('/'))return res.code(400).send({error:'absolute_path_required'});try{await ptero.writeFile(s.ptero_identifier,key(),file,String(req.body?.content??''));return {ok:true};}catch(e){const z=ptero.pteroError(e);return res.code(z.statusCode).send({error:z.message});}});
  app.post('/control/servers/:id/folder',async(req:any,res:any)=>{const s=await server(req,res);if(!s)return res.code(404).send({error:'server_not_found'});const root=String(req.body?.root||'/'),name=String(req.body?.name||'');if(!name||name.includes('/')||name.includes('..'))return res.code(400).send({error:'invalid_folder_name'});try{await ptero.createFolder(s.ptero_identifier,key(),root,name);return {ok:true};}catch(e){const z=ptero.pteroError(e);return res.code(z.statusCode).send({error:z.message});}});
  app.post('/control/servers/:id/files/delete',async(req:any,res:any)=>{const s=await server(req,res);if(!s)return res.code(404).send({error:'server_not_found'});const root=String(req.body?.root||'/'),files=Array.isArray(req.body?.files)?req.body.files.map(String):[];if(!files.length)return res.code(400).send({error:'files_required'});try{await ptero.deleteFiles(s.ptero_identifier,key(),root,files);return {ok:true};}catch(e){const z=ptero.pteroError(e);return res.code(z.statusCode).send({error:z.message});}});
  app.post('/control/servers/:id/files/rename',async(req:any,res:any)=>{const s=await server(req,res);if(!s)return res.code(404).send({error:'server_not_found'});const root=String(req.body?.root||'/'),files=Array.isArray(req.body?.files)?req.body.files:[];if(!files.length)return res.code(400).send({error:'files_required'});try{await ptero.renameFiles(s.ptero_identifier,key(),root,files.map((f:any)=>({from:String(f.from),to:String(f.to)})));return {ok:true};}catch(e){const z=ptero.pteroError(e);return res.code(z.statusCode).send({error:z.message});}});
  app.post('/control/servers/:id/console',async(req:any,res:any)=>{const s=await server(req,res);if(!s)return res.code(404).send({error:'server_not_found'});if(s.suspended)return res.code(409).send({error:'server_suspended'});const command=String(req.body?.command||'').trim();if(!command||command.length>4096)return res.code(400).send({error:'invalid_command'});try{await ptero.sendCommand(s.ptero_identifier,key(),command);return {ok:true};}catch(e){const z=ptero.pteroError(e);return res.code(z.statusCode).send({error:z.message});}});
  app.get('/control/servers/:id/backups',async(req:any,res:any)=>{const s=await server(req,res);if(!s)return res.code(404).send({error:'server_not_found'});try{return {backups:await ptero.listBackups(s.ptero_identifier,key())};}catch(e){const z=ptero.pteroError(e);return res.code(z.statusCode).send({error:z.message});}});
  app.post('/control/servers/:id/backups',async(req:any,res:any)=>{const s=await server(req,res);if(!s)return res.code(404).send({error:'server_not_found'});try{return {backup:await ptero.createBackup(s.ptero_identifier,key(),req.body?.name?String(req.body.name):undefined)};}catch(e){const z=ptero.pteroError(e);return res.code(z.statusCode).send({error:z.message});}});
  app.delete('/control/servers/:id/backups/:backup',async(req:any,res:any)=>{const s=await server(req,res);if(!s)return res.code(404).send({error:'server_not_found'});try{await ptero.deleteBackup(s.ptero_identifier,key(),String(req.params.backup));return {ok:true};}catch(e){const z=ptero.pteroError(e);return res.code(z.statusCode).send({error:z.message});}});
  app.post('/control/servers/:id/backups/:backup/restore',async(req:any,res:any)=>{const s=await server(req,res);if(!s)return res.code(404).send({error:'server_not_found'});try{await ptero.restoreBackup(s.ptero_identifier,key(),String(req.params.backup));return {ok:true};}catch(e){const z=ptero.pteroError(e);return res.code(z.statusCode).send({error:z.message});}});
  app.get('/control/servers/:id/allocations',async(req:any,res:any)=>{const s=await server(req,res);if(!s)return res.code(404).send({error:'server_not_found'});try{return {allocations:await ptero.listServerAllocations(s.ptero_identifier,key())};}catch(e){const z=ptero.pteroError(e);return res.code(z.statusCode).send({error:z.message});}});
  app.get('/control/servers/:id/databases',async(req:any,res:any)=>{const s=await server(req,res);if(!s)return res.code(404).send({error:'server_not_found'});try{return {databases:await ptero.listServerDatabases(s.ptero_identifier,key())};}catch(e){const z=ptero.pteroError(e);return res.code(z.statusCode).send({error:z.message});}});
  app.put('/control/servers/:id/startup',async(req:any,res:any)=>{const s=await server(req,res);if(!s)return res.code(404).send({error:'server_not_found'});if(s.suspended)return res.code(409).send({error:'server_suspended'});try{return await ptero.updateStartup(s.ptero_identifier,key(),req.body||{});}catch(e){const z=ptero.pteroError(e);return res.code(z.statusCode).send({error:z.message});}});
}
