'use client';
import {useEffect,useState} from 'react';
async function api(path:string,options:RequestInit={}){const r=await fetch(path,{...options,credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d;}
function Button({children,onClick,danger=false,disabled=false}:{children:any,onClick:()=>void,danger?:boolean,disabled?:boolean}){return <button className={`btn ${danger?'danger':''}`} disabled={disabled} onClick={onClick}>{children}</button>}
export default function Admin(){const[stats,setStats]=useState<any>(null),[users,setUsers]=useState<any[]>([]),[servers,setServers]=useState<any[]>([]),[selectedUser,setSelectedUser]=useState<any>(null),[selectedServer,setSelectedServer]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){try{setError('');const[s,u,v]=await Promise.all([api('/staff/stats/extended'),api('/staff/accounts'),api('/staff/servers')]);setStats(s);setUsers(u.accounts);setServers(v.servers);}catch(e:any){setError(e.message)}}
 useEffect(()=>{void load();const t=setInterval(()=>void load(),10000);return()=>clearInterval(t)},[]);
 async function action(path:string,body:any={}){setBusy(true);setError('');setNotice('');try{const d=await api(path,{method:'POST',body:JSON.stringify(body)});if(d.confirmRequired){if(!window.confirm(`This is a destructive operation. Continue?`))return;return await action(path,{...body,confirm:true});}setNotice('Operation completed successfully.');await load();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function inspectUser(id:string){try{setSelectedUser(await api(`/staff/users/${id}`));}catch(e:any){setError(e.message)}}
 return <main className="shell"><header className="top"><a className="menu" href="/dashboard">Back</a><div className="brand">Atx<span>Cloud</span></div><div className="muted">Admin Control Center</div></header><section className="main">
 <div className="hero"><div><div className="eyebrow">Operations</div><h1 className="title">Control center</h1><p className="muted">Live administrative state. Every privileged mutation is authorized server-side and destructive operations require confirmation.</p></div></div>
 {error&&<div className="card error">{error}</div>}{notice&&<div className="card">{notice}</div>}
 <div className="grid"><div className="card"><div className="muted">Users</div><div className="metric">{stats?.users??0}</div></div><div className="card"><div className="muted">Blacklisted</div><div className="metric">{stats?.blacklisted??0}</div></div><div className="card"><div className="muted">Minecraft</div><div className="metric">{stats?.minecraft?.total??0}</div><small className="muted">{stats?.minecraft?.running??0} running · {stats?.minecraft?.suspended??0} suspended</small></div><div className="card"><div className="muted">Bot / Code</div><div className="metric">{stats?.code?.total??0}</div><small className="muted">{stats?.code?.running??0} running · {stats?.code?.suspended??0} suspended</small></div></div>
 <section className="section"><div className="hero"><div><div className="eyebrow">Capacity</div><h2>Node slots</h2></div></div><div className="grid">{stats?.nodes?.map((n:any)=><div className="card" key={n.id}><strong>{n.name}</strong><p className="muted">Minecraft {n.minecraft_slot_total??0} total · Code {n.code_slot_total??0} total</p><p className="muted">Node {n.enabled?'enabled':'disabled'} · Pterodactyl #{n.ptero_node_id}</p></div>)}</div></section>
 <section className="section"><div className="hero"><div><div className="eyebrow">Users</div><h2>Account management</h2></div></div><div className="servers">{users.slice(0,100).map(u=><article className="card server" key={u.discordId}><div className="status"><span className={`dot ${u.blacklisted?'':'live'}`}/>{u.blacklisted?'Blacklisted':'Active'}</div><h3>{u.user}</h3><p className="muted">{u.email||'No email'} · {u.coins} coins</p><div className="actions"><Button onClick={()=>void inspectUser(u.id)}>Inspect</Button><Button danger={u.blacklisted===false} onClick={()=>void action(`/staff/users/${u.id}/action`,{action:u.blacklisted?'unblacklist':'blacklist'})}>{u.blacklisted?'Unblacklist':'Blacklist'}</Button><Button onClick={()=>void action(`/staff/users/${u.id}/action`,{action:'reset-coins'})}>Reset coins</Button><Button danger onClick={()=>void action(`/staff/users/${u.id}/action`,{action:'delete'})}>Delete user</Button></div></article>)}</div></section>
 {selectedUser&&<section className="section"><div className="card"><div className="eyebrow">User detail</div><h2>{selectedUser.user.username}</h2><p className="muted">{selectedUser.user.email||'No email'} · {selectedUser.user.discord_id}</p><div className="grid"><div><b>Available coins</b><div className="metric">{selectedUser.user.coins}</div></div><div><b>Earned</b><div className="metric">{selectedUser.coinSummary?.earned??0}</div></div><div><b>Spent</b><div className="metric">{selectedUser.coinSummary?.spent??0}</div></div></div><h3>Owned servers</h3>{selectedUser.servers?.map((s:any)=><div className="actions" style={{justifyContent:'space-between'}} key={s.public_id}><span>{s.name} · {s.public_id}</span><span className="muted">{s.suspended?'Suspended':'Active'}</span></div>)}</div></section>}
 <section className="section"><div className="hero"><div><div className="eyebrow">Servers</div><h2>Lifecycle operations</h2></div></div><div className="servers">{servers.slice(0,100).map(s=><article className="card server" key={s.public_id}><div className="status"><span className={`dot ${!s.suspended?'live':''}`}/>{s.suspended?'Suspended':'Active'}</div><h3>{s.name}</h3><p className="muted">{s.public_id} · {s.owner} · {s.node||'No node'} · {s.category}</p><div className="actions"><Button onClick={()=>void action(`/staff/servers/${s.public_id}/action`,{action:'start'})} disabled={busy||s.suspended}>Start</Button><Button onClick={()=>void action(`/staff/servers/${s.public_id}/action`,{action:'restart'})} disabled={busy||s.suspended}>Restart</Button><Button onClick={()=>void action(`/staff/servers/${s.public_id}/action`,{action:s.suspended?'unsuspend':'suspend'})}>{s.suspended?'Unsuspend':'Suspend'}</Button><Button danger onClick={()=>void action(`/staff/servers/${s.public_id}/action`,{action:'delete'})}>Delete</Button></div></article>)}</div></section>
 <section className="section"><div className="card"><div className="eyebrow">Purge</div><h2>Bulk server cleanup</h2><p className="muted">Select a policy and the API will calculate the real matching server count before any deletion.</p><div className="actions"><select id="purgeMode" defaultValue="suspended"><option value="suspended">Suspended servers</option><option value="offline">Offline servers</option><option value="blacklisted">Blacklisted users' servers</option></select><Button danger onClick={async()=>{const mode=(document.getElementById('purgeMode') as HTMLSelectElement).value;try{const d=await api('/staff/purge',{method:'POST',body:JSON.stringify({mode,confirm:false})});if(!window.confirm(`This action will delete ${d.count} servers. Are you sure?`))return;await action('/staff/purge',{mode,confirm:true});}catch(e:any){setError(e.message)}}}>Calculate and purge</Button></div></div></section>
 </section></main>}
