'use client';
import {useEffect,useState} from 'react';
const API=(process.env.NEXT_PUBLIC_API_URL||'http://127.0.0.1:4000').replace(/\/$/,'');
export default function Dashboard(){const [open,setOpen]=useState(false);const [me,setMe]=useState<any>(null);const [servers,setServers]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 async function load(){try{const a=await fetch(`${API}/me`,{credentials:'include'});if(!a.ok)throw new Error('Your session has expired.');const m=await a.json();const s=await fetch(`${API}/servers`,{credentials:'include'});setMe(m);setServers(await s.json());}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function power(id:string,signal:string){const r=await fetch(`${API}/servers/${id}/power`,{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({signal})});if(!r.ok){const x=await r.json();return alert(x.error)}load()}
 if(loading)return <main className="shell"><div className="main"><p className="muted">Loading control plane…</p></div></main>;
 if(error)return <main className="login"><section className="card login-card"><div className="login-logo">Atx<span>Cloud</span></div><p>{error}</p><a className="oauth" href="/">Return to login</a></section></main>;
 return <main className="shell"><header className="top"><button className="menu" onClick={()=>setOpen(!open)}>Menu</button><div className="brand">Atx<span>Cloud</span></div><div className="muted">{me.user.username}</div></header><aside className={`drawer ${open?'open':''}`}><nav className="nav"><a className="active" href="#overview">Overview</a><a href="#servers">Servers</a><a href="#account">Account</a><a href="#coins">ATX Coins</a><a href="#referrals">Referrals</a><a href="#rewards">Rewards</a><a href="#store">Store</a>{me.staff&&<a href="#admin">Admin</a>}</nav></aside><section className="main"><div className="hero"><div><div className="eyebrow">Control plane</div><h1 className="title">Good to see you, {me.user.username}.</h1><div className="muted">Everything in one place. Live state comes from AtxCloud and Pterodactyl.</div></div></div><div className="grid"><div className="card"><div className="muted">ATX Coins</div><div className="metric">{me.user.coins}</div></div><div className="card"><div className="muted">Servers</div><div className="metric">{servers.length}</div></div><div className="card"><div className="muted">Account</div><div className="metric">Active</div></div><div className="card"><div className="muted">Access</div><div className="metric">{me.staff?'Staff':'User'}</div></div></div><div className="section" id="servers"><div className="hero"><div><div className="eyebrow">Infrastructure</div><h2>Servers</h2></div><button className="btn primary">Create server</button></div><div className="servers">{servers.map(s=><article className="card server" key={s.public_id}><div className="status"><span className="dot"></span>{s.suspended?'Suspended':'Managed'}</div><h3>{s.name}</h3><div className="muted">{s.public_id} · {s.category} · {s.node_name||'Unassigned node'}</div><div className="actions"><button className="btn primary" onClick={()=>power(s.public_id,'start')}>Start</button><button className="btn" onClick={()=>power(s.public_id,'restart')}>Restart</button><button className="btn" onClick={()=>power(s.public_id,'stop')}>Stop</button><button className="btn" onClick={()=>power(s.public_id,'kill')}>Kill</button></div></article>)}{!servers.length&&<div className="card"><h3>No servers yet</h3><p className="muted">Create your first server when your account is provisioned.</p></div>}</div></div></section></main>}
