'use client';
import {useEffect,useState} from 'react';

type Server={public_id:string;name:string;category:string;version?:string;suspended:boolean;node_name?:string;egg_id?:number};
type FileRow={name:string;size:number;is_file:boolean;mode:string};
async function api(path:string,options:RequestInit={}){const r=await fetch(path,{...options,credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d;}
function mb(n:number){return `${Math.round((Number(n)||0)/1048576)} MB`;}
function gb(n:number){return `${((Number(n)||0)/1073741824).toFixed(2)} GB`;}
export default function ServerWorkspace({params}:{params:{id:string}}){
 const id=params.id; const [data,setData]=useState<any>(null); const [files,setFiles]=useState<FileRow[]>([]); const [dir,setDir]=useState('/'); const [content,setContent]=useState(''); const [selected,setSelected]=useState(''); const [consoleInput,setConsoleInput]=useState(''); const [log,setLog]=useState<string[]>([]); const [busy,setBusy]=useState(''); const [error,setError]=useState('');
 const load=async()=>{try{setData(await api(`/servers/${id}`));setFiles((await api(`/control/servers/${id}/files?directory=${encodeURIComponent(dir)}`)).files||[]);setError('');}catch(e:any){setError(e.message||'Unable to load server');}};
 useEffect(()=>{void load();const t=setInterval(()=>void load(),5000);return()=>clearInterval(t)},[id,dir]);
 async function action(signal:string){setBusy(signal);try{await api(`/servers/${id}/power`,{method:'POST',body:JSON.stringify({signal})});await load();}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function openFile(name:string){const path=(dir==='/'?'':dir)+'/'+name;setSelected(path);try{const x=await api(`/control/servers/${id}/file?path=${encodeURIComponent(path)}`);setContent(String(x.content??''));}catch(e:any){setError(e.message)}}
 async function saveFile(){if(!selected)return;setBusy('save');try{await api(`/control/servers/${id}/file`,{method:'PUT',body:JSON.stringify({path:selected,content})});setLog(x=>[`Saved ${selected}`,...x].slice(0,30));}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function send(){const command=consoleInput.trim();if(!command)return;setBusy('console');try{await api(`/control/servers/${id}/console`,{method:'POST',body:JSON.stringify({command})});setLog(x=>[`> ${command}`,...x].slice(0,30));setConsoleInput('');}catch(e:any){setError(e.message)}finally{setBusy('')}}
 if(error&&!data)return <main className="main"><div className="card"><h2>Server unavailable</h2><p className="muted">{error}</p><a className="btn" href="/dashboard/servers">Back to servers</a></div></main>;
 const s:Server=data?.server||{}; const r=data?.resource?.current||data?.resource||{};
 return <main className="main"><div className="hero"><div><div className="eyebrow">Server workspace</div><h1 className="title">{s.name||id}</h1><div className="muted">{s.public_id} · {s.category} · {s.version||'Version not set'}</div></div><a className="btn" href="/dashboard/servers">All servers</a></div>
  {error&&<div className="card error">{error}</div>}
  <div className="grid"><div className="card"><div className="muted">Status</div><div className="metric">{r.state||'unknown'}</div></div><div className="card"><div className="muted">RAM</div><div className="metric">{mb(r.memory_bytes)} / 1024 MB</div></div><div className="card"><div className="muted">CPU</div><div className="metric">{Math.round(Number(r.cpu_absolute)||0)}% / 70%</div></div><div className="card"><div className="muted">Disk</div><div className="metric">{gb(r.disk_bytes)} / 5 GB</div></div></div>
  <section className="section"><div className="card"><div className="actions"><button className="btn primary" disabled={!!busy||s.suspended} onClick={()=>void action('start')}>{busy==='start'?'Starting…':'Start'}</button><button className="btn" disabled={!!busy||s.suspended} onClick={()=>void action('restart')}>{busy==='restart'?'Restarting…':'Restart'}</button><button className="btn" disabled={!!busy||s.suspended} onClick={()=>void action('stop')}>{busy==='stop'?'Stopping…':'Stop'}</button><button className="btn" disabled={!!busy||s.suspended} onClick={()=>void action('kill')}>{busy==='kill'?'Killing…':'Kill'}</button></div></div></section>
  <section className="section"><div className="hero"><div><div className="eyebrow">Console</div><h2>Live command console</h2></div></div><div className="card"><div className="console">{log.length?log.map((x,i)=><div key={i}>{x}</div>):<span className="muted">No commands sent from this session.</span>}</div><div className="actions"><input className="input" value={consoleInput} onChange={e=>setConsoleInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void send()}} placeholder="Enter a server command"/><button className="btn primary" disabled={busy==='console'} onClick={()=>void send()}>Send</button></div></div></section>
  <section className="section"><div className="hero"><div><div className="eyebrow">Files</div><h2>{dir}</h2></div><button className="btn" onClick={()=>setDir(dir==='/'?'/':dir.split('/').slice(0,-1).join('/')||'/')}>Up</button></div><div className="card"><div className="file-list">{files.map(f=><button className="file-row" key={f.name} onClick={()=>f.is_file?void openFile(f.name):setDir((dir==='/'?'':dir)+'/'+f.name)}><span>{f.is_file?'File':'Folder'}</span><strong>{f.name}</strong><span className="muted">{f.is_file?`${Math.round(f.size/1024)} KB`:''}</span></button>)}{!files.length&&<div className="muted">Directory is empty.</div>}</div></div></section>
  {selected&&<section className="section"><div className="hero"><div><div className="eyebrow">Editor</div><h2>{selected}</h2></div><button className="btn primary" disabled={busy==='save'} onClick={()=>void saveFile()}>{busy==='save'?'Saving…':'Save file'}</button></div><textarea className="editor" value={content} onChange={e=>setContent(e.target.value)} spellCheck={false}/></section>}
 </main>;
}
