'use client';
import {useEffect,useState} from 'react';
type Server={public_id:string;name:string;category:string;version?:string;suspended:boolean;node_name?:string};type FileRow={name:string;size:number;is_file:boolean;mode:string};
async function api(path:string,options:RequestInit={}){const r=await fetch(path,{...options,credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d;}
function mb(n:number){return `${Math.round((Number(n)||0)/1048576)} MB`}function gb(n:number){return `${((Number(n)||0)/1073741824).toFixed(2)} GB`}
export default function ServerWorkspace({params}:{params:{id:string}}){const id=params.id;const[data,setData]=useState<any>(null),[files,setFiles]=useState<FileRow[]>([]),[backups,setBackups]=useState<any[]>([]),[dir,setDir]=useState('/'),[content,setContent]=useState(''),[selected,setSelected]=useState(''),[command,setCommand]=useState(''),[log,setLog]=useState<string[]>([]),[tab,setTab]=useState('overview'),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const load=async()=>{try{setData(await api(`/servers/${id}`));if(tab==='files')setFiles((await api(`/control/servers/${id}/files?directory=${encodeURIComponent(dir)}`)).files||[]);if(tab==='backups')setBackups((await api(`/control/servers/${id}/backups`)).backups||[]);setError('')}catch(e:any){setError(e.message||'Unable to load server')}};useEffect(()=>{void load();const t=setInterval(()=>void load(),5000);return()=>clearInterval(t)},[id,dir,tab]);
 async function power(signal:string){setBusy(signal);try{await api(`/servers/${id}/power`,{method:'POST',body:JSON.stringify({signal})});await load()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function send(){const v=command.trim();if(!v)return;setBusy('console');try{await api(`/control/servers/${id}/console`,{method:'POST',body:JSON.stringify({command:v})});setLog(x=>[`> ${v}`,...x].slice(0,40));setCommand('')}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function openFile(name:string){const p=(dir==='/'?'':dir)+'/'+name;setSelected(p);try{const x=await api(`/control/servers/${id}/file?path=${encodeURIComponent(p)}`);setContent(String(x.content??''))}catch(e:any){setError(e.message)}}
 async function save(){if(!selected)return;setBusy('save');try{await api(`/control/servers/${id}/file`,{method:'PUT',body:JSON.stringify({path:selected,content})});setLog(x=>[`Saved ${selected}`,...x].slice(0,40))}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function createBackup(){setBusy('backup');try{await api(`/control/servers/${id}/backups`,{method:'POST',body:JSON.stringify({name:`AtxCloud ${new Date().toISOString().slice(0,19).replace('T',' ')}`})});await load()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function deleteBackup(uuid:string){if(!confirm('Delete this backup permanently?'))return;setBusy('delete-backup');try{await api(`/control/servers/${id}/backups/${encodeURIComponent(uuid)}`,{method:'DELETE'});await load()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 if(error&&!data)return <main className="main"><div className="card"><h2>Server unavailable</h2><p className="muted">{error}</p><a className="btn" href="/dashboard/servers">Back to servers</a></div></main>;const s:Server=data?.server||{},r=data?.resource?.current||data?.resource||{},players=r.players||{};
 return <main className="main"><div className="hero"><div><div className="eyebrow">Server workspace</div><h1 className="title">{s.name||id}</h1><div className="muted">{s.public_id} · {s.category} · {s.version||'Version not set'} · {s.node_name||'Node unavailable'}</div></div><a className="btn" href="/dashboard/servers">All servers</a></div>{error&&<div className="card error">{error}</div>}
 <div className="actions tabs"><button className={`btn ${tab==='overview'?'primary':''}`} onClick={()=>setTab('overview')}>Overview</button><button className={`btn ${tab==='console'?'primary':''}`} onClick={()=>setTab('console')}>Console</button><button className={`btn ${tab==='files'?'primary':''}`} onClick={()=>setTab('files')}>Files</button><button className={`btn ${tab==='backups'?'primary':''}`} onClick={()=>setTab('backups')}>Backups</button><button className={`btn ${tab==='players'?'primary':''}`} onClick={()=>setTab('players')}>Players</button><button className={`btn ${tab==='startup'?'primary':''}`} onClick={()=>setTab('startup')}>Startup</button></div>
 <div className="grid"><div className="card"><div className="muted">Status</div><div className="metric">{r.state||'unknown'}</div></div><div className="card"><div className="muted">RAM</div><div className="metric">{mb(r.memory_bytes)} / 1024 MB</div></div><div className="card"><div className="muted">CPU</div><div className="metric">{Math.round(Number(r.cpu_absolute)||0)}% / 70%</div></div><div className="card"><div className="muted">Disk</div><div className="metric">{gb(r.disk_bytes)} / 5 GB</div></div></div>
 <section className="section"><div className="card"><div className="actions"><button className="btn primary" disabled={!!busy||s.suspended} onClick={()=>void power('start')}>{busy==='start'?'Starting…':'Start'}</button><button className="btn" disabled={!!busy||s.suspended} onClick={()=>void power('restart')}>{busy==='restart'?'Restarting…':'Restart'}</button><button className="btn" disabled={!!busy||s.suspended} onClick={()=>void power('stop')}>{busy==='stop'?'Stopping…':'Stop'}</button><button className="btn" disabled={!!busy||s.suspended} onClick={()=>void power('kill')}>{busy==='kill'?'Killing…':'Kill'}</button></div></div></section>
 {tab==='overview'&&<section className="section"><div className="grid"><div className="card"><div className="muted">Players</div><div className="metric">{players.current??0} / {players.max??0}</div></div><div className="card"><div className="muted">Backups</div><div className="metric">{backups.length} / 3</div></div><div className="card"><div className="muted">Server ID</div><div className="metric" style={{fontSize:20}}>{s.public_id}</div></div><div className="card"><div className="muted">Software</div><div className="metric" style={{fontSize:20}}>{s.category}</div></div></div></section>}
 {tab==='console'&&<section className="section"><div className="card"><div className="eyebrow">Console</div><h2>Live command console</h2><div className="console">{log.length?log.map((x,i)=><div key={i}>{x}</div>):<span className="muted">Commands sent from this session will appear here.</span>}</div><div className="actions"><input className="input" value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void send()}} placeholder="Enter a server command"/><button className="btn primary" disabled={busy==='console'} onClick={()=>void send()}>Send</button></div></div></section>}
 {tab==='files'&&<section className="section"><div className="hero"><div><div className="eyebrow">Files</div><h2>{dir}</h2></div><button className="btn" onClick={()=>setDir(dir==='/'?'/':dir.split('/').slice(0,-1).join('/')||'/')}>Up</button></div><div className="card"><div className="file-list">{files.map(f=><button className="file-row" key={f.name} onClick={()=>f.is_file?void openFile(f.name):setDir((dir==='/'?'':dir)+'/'+f.name)}><span>{f.is_file?'File':'Folder'}</span><strong>{f.name}</strong><span className="muted">{f.is_file?`${Math.round(f.size/1024)} KB`:''}</span></button>)}{!files.length&&<div className="muted">Directory is empty.</div>}</div></div>{selected&&<div className="section"><div className="hero"><h2>{selected}</h2><button className="btn primary" disabled={busy==='save'} onClick={()=>void save()}>{busy==='save'?'Saving…':'Save file'}</button></div><textarea className="editor" value={content} onChange={e=>setContent(e.target.value)} spellCheck={false}/></div>}</section>}
 {tab==='backups'&&<section className="section"><div className="hero"><div><div className="eyebrow">Backups</div><h2>Server snapshots</h2></div><button className="btn primary" disabled={busy==='backup'} onClick={()=>void createBackup()}>{busy==='backup'?'Creating…':'Create backup'}</button></div><div className="servers">{backups.map((b:any)=><article className="card server" key={b.uuid||b.id}><h3>{b.name||'Unnamed backup'}</h3><p className="muted">{b.uuid||b.id} · {b.bytes?gb(b.bytes):'Size unavailable'} · {b.completed_at||'Pending'}</p><button className="btn" disabled={busy==='delete-backup'} onClick={()=>void deleteBackup(String(b.uuid||b.id))}>Delete</button></article>)}{!backups.length&&<div className="card muted">No backups available.</div>}</div></section>}
 {tab==='players'&&<section className="section"><div className="card"><div className="eyebrow">Players</div><h2>Live player state</h2><div className="metric">{players.current??0} / {players.max??0}</div><p className="muted">{Array.isArray(players.list)&&players.list.length?players.list.map((p:any)=>p.name||p).join(' · '):'No player names are currently reported by the server.'}</p></div></section>}
 {tab==='startup'&&<section className="section"><div className="card"><div className="eyebrow">Startup</div><h2>Runtime configuration</h2><p className="muted">Startup variables remain controlled by the Pterodactyl egg. The AtxCloud application key is never exposed to the browser.</p><p className="muted">This workspace is ready for the startup editor once the selected egg exposes its variable metadata.</p></div></section>}
 </main>}
