import {Client,GatewayIntentBits,REST,Routes,SlashCommandBuilder,ActionRowBuilder,StringSelectMenuBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,ChatInputCommandInteraction,Interaction,Message} from 'discord.js';
import crypto from 'node:crypto';
const API=(process.env.API_URL||'http://api:4000').replace(/\/$/,'');
const SECRET=process.env.ATXCLOUD_INTERNAL_SECRET||'';
const bot=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent]});
const commands=[
 new SlashCommandBuilder().setName('manage-server').setDescription('Manage your AtxCloud servers'),
 new SlashCommandBuilder().setName('my-account').setDescription('View your AtxCloud account'),
 new SlashCommandBuilder().setName('gift-coins').setDescription('Transfer coins').addUserOption(o=>o.setName('user').setDescription('Recipient').setRequired(true)).addIntegerOption(o=>o.setName('coins').setDescription('Amount').setRequired(true).setMinValue(1)),
 new SlashCommandBuilder().setName('share-access').setDescription('Share server access').addStringOption(o=>o.setName('server').setDescription('Server ID').setRequired(true)).addUserOption(o=>o.setName('user').setDescription('User').setRequired(true)),
 new SlashCommandBuilder().setName('remove-access').setDescription('Remove server access').addStringOption(o=>o.setName('server').setDescription('Server ID').setRequired(true)).addUserOption(o=>o.setName('user').setDescription('User').setRequired(true)),
 new SlashCommandBuilder().setName('staff-accounts').setDescription('Staff: list accounts'),new SlashCommandBuilder().setName('staff-servers').setDescription('Staff: list servers'),
 new SlashCommandBuilder().setName('staff-manage-user').setDescription('Staff: manage a user').addUserOption(o=>o.setName('user').setDescription('User').setRequired(true)),new SlashCommandBuilder().setName('staff-manage-server').setDescription('Staff: manage a server').addStringOption(o=>o.setName('server').setDescription('Server ID').setRequired(true)),new SlashCommandBuilder().setName('staff-stats').setDescription('Staff: system statistics'),new SlashCommandBuilder().setName('staff-purge-servers').setDescription('Staff: purge servers').addStringOption(o=>o.setName('type').setDescription('Selection').setRequired(true).addChoices({name:'Suspended',value:'suspended'},{name:'Offline',value:'offline'},{name:'Blacklisted',value:'blacklisted'}))
].map(x=>x.toJSON());
async function api(path:string,discordId:string,init:any={}){const r=await fetch(`${API}${path}`,{...init,headers:{'content-type':'application/json','x-atx-internal-secret':SECRET,'x-discord-user':discordId,...(init.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`API ${r.status}`);return data;}
function embedServer(s:any,r:any){const mem=r?.current??r;const state=mem?.state||'unknown';const ram=mem?.memory_bytes?`${Math.round(mem.memory_bytes/1048576)} MB`:'0 MB';const disk=mem?.disk_bytes?`${(mem.disk_bytes/1073741824).toFixed(2)} GB`:'0 GB';return new EmbedBuilder().setTitle(s.name).setDescription(`Server ID: **${s.public_id}**\nSoftware: **${s.egg_id}**\nVersion: **${s.version||'Not set'}**\nStatus: **${state}**\nRAM: **${ram}**\nCPU: **${Math.round(mem?.cpu_absolute||0)}%**\nSSD: **${disk}**`).setColor(0xe0002a);}
function powerRow(id:string,user:string){return new ActionRowBuilder<ButtonBuilder>().addComponents(...(['start','stop','restart','kill'] as const).map(x=>new ButtonBuilder().setCustomId(`power:${user}:${id}:${x}`).setLabel(x[0].toUpperCase()+x.slice(1)).setStyle(x==='kill'?ButtonStyle.Danger:x==='start'?ButtonStyle.Success:ButtonStyle.Secondary)));}
function confirmRow(id:string){return new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`confirm:${id}`).setLabel('Confirm').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId(`cancel:${id}`).setLabel('Cancel').setStyle(ButtonStyle.Secondary));}
function key(){return crypto.randomBytes(18).toString('hex');}

bot.once('ready',async()=>{const rest=new REST({version:'10'}).setToken(process.env.DISCORD_BOT_TOKEN!);await rest.put(Routes.applicationGuildCommands(bot.user!.id,process.env.DISCORD_GUILD_ID!),{body:commands});console.log(`AtxCloud bot ready as ${bot.user?.tag}`);});

bot.on('interactionCreate',async(i:Interaction)=>{try{
 if(i.isButton()){
  const p=i.customId.split(':');
  if(p[0]==='power'){if(i.user.id!==p[1])return i.reply({content:'This control panel belongs to another user.',ephemeral:true});await i.deferUpdate();await api(`/internal/servers/${p[2]}/power`,i.user.id,{method:'POST',body:JSON.stringify({signal:p[3]})});const fresh=await api(`/internal/servers/${p[2]}`,i.user.id);return i.editReply({embeds:[embedServer(fresh.server,fresh.resource)],components:[powerRow(p[2],i.user.id)]});}
  if(p[0]==='cancel'||p[0]==='confirm'){if(i.user.id!==p[1])return i.reply({content:'Only the invoking user can confirm this action.',ephemeral:true});return i.update({content:p[0]==='cancel'?'Cancelled.':'Confirmation received.',components:[]});}
 }
 if(i.isStringSelectMenu()&&i.customId.startsWith('select:')){const owner=i.customId.split(':')[1];if(i.user.id!==owner)return i.reply({content:'This selector belongs to another user.',ephemeral:true});const s=await api(`/internal/servers/${i.values[0]}`,i.user.id);return i.update({content:'Live server controls',embeds:[embedServer(s.server,s.resource)],components:[powerRow(s.server.public_id,i.user.id)]});}
 if(!i.isChatInputCommand())return;
 const user=i.user.id;
 if(i.commandName==='manage-server'){const list=await api('/internal/servers',user);if(!list.length)return i.reply({content:'You do not have any servers.',ephemeral:true});const menu=new StringSelectMenuBuilder().setCustomId(`select:${user}`).setPlaceholder('Select a server').addOptions(list.slice(0,25).map((s:any)=>({label:s.name.slice(0,100),value:s.public_id,description:s.public_id})));return i.reply({content:'Select a server to manage.',components:[new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(menu)]});}
 if(i.commandName==='my-account'){const m=await api('/internal/me',user);const e=new EmbedBuilder().setTitle('AtxCloud Account').setDescription(`User: **${m.user.username}**\nEmail: **${m.user.email||'Not available'}**\nCoins: **${m.user.coins}**\nServers: **${m.servers.length}**\nCreated: **${new Date(m.user.createdAt).toLocaleString()}**`).setColor(0xe0002a);return i.reply({embeds:[e],components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setLabel('Open dashboard').setStyle(ButtonStyle.Link).setURL(process.env.DASHBOARD_URL||'https://dash.atxcloud.ggff.net'))]});}
 if(i.commandName==='gift-coins'){const target=i.options.getUser('user',true),coins=i.options.getInteger('coins',true),id=key();return i.reply({content:`Transfer **${coins}** coins to ${target}?`,components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`gift:${user}:${target.id}:${coins}:${id}`).setLabel('Confirm transfer').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId(`cancel:${user}:${id}`).setLabel('Cancel').setStyle(ButtonStyle.Secondary))]});}
 if(i.commandName==='share-access'||i.commandName==='remove-access'){const server=i.options.getString('server',true),target=i.options.getUser('user',true),action=i.commandName==='share-access'?'add':'remove',id=key();return i.reply({content:`Confirm **${action}** access for ${target} on **${server}**?`,components:[new ActionRowBuilder<ButtonBuilder>().setCustomId(`access:${user}:${action}:${server}:${target.id}:${id}`).setLabel('Confirm').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId(`cancel:${user}:${id}`).setLabel('Cancel').setStyle(ButtonStyle.Secondary)]});}
 if(i.commandName.startsWith('staff-'))return staff(i as ChatInputCommandInteraction);
 }catch(e:any){if(i.isRepliable())return i.replied||i.deferred?i.followUp({content:e.message||'Operation failed',ephemeral:true}):i.reply({content:e.message||'Operation failed',ephemeral:true});}}
});

bot.on('interactionCreate',async(i:Interaction)=>{if(!i.isButton())return;const p=i.customId.split(':');try{
 if(p[0]==='gift'){if(i.user.id!==p[1])return i.reply({content:'Only the invoking user can confirm this transfer.',ephemeral:true});await api('/internal/coins/gift',i.user.id,{method:'POST',body:JSON.stringify({targetDiscordId:p[2],coins:Number(p[3]),idempotencyKey:p[4]})});return i.update({content:`Transferred **${p[3]}** coins successfully.`,components:[]});}
 if(p[0]==='access'){if(i.user.id!==p[1])return i.reply({content:'Only the invoking user can confirm this action.',ephemeral:true});await api('/internal/access',i.user.id,{method:'POST',body:JSON.stringify({action:p[2],serverId:p[3],targetDiscordId:p[4]})});return i.update({content:`Access ${p[2]==='add'?'granted':'removed'} successfully.`,components:[]});}
 }catch(e:any){return i.reply({content:e.message||'Operation failed',ephemeral:true});}});

async function staff(i:ChatInputCommandInteraction){const check=await api('/internal/staff/check',i.user.id);if(!check.staff)return i.reply({content:'Staff access required.',ephemeral:true});
 if(i.commandName==='staff-accounts'){const x=await api('/internal/staff/accounts',i.user.id);const text=x.accounts.slice(0,25).map((u:any)=>`**${u.username}** • ${u.email||'no email'} • ${u.blacklisted?'blacklisted':'active'}`).join('\n')||'No accounts';return i.reply({embeds:[new EmbedBuilder().setTitle('AtxCloud Accounts').setDescription(text).setColor(0xe0002a)]});}
 if(i.commandName==='staff-servers'){const x=await api('/internal/staff/servers',i.user.id);const text=x.servers.slice(0,25).map((s:any)=>`**${s.name}** • ${s.public_id} • ${s.owner}`).join('\n')||'No servers';return i.reply({embeds:[new EmbedBuilder().setTitle('AtxCloud Servers').setDescription(text).setColor(0xe0002a)]});}
 if(i.commandName==='staff-stats'){const s=await api('/internal/staff/stats',i.user.id);return i.reply({embeds:[new EmbedBuilder().setTitle('AtxCloud Staff Stats').setDescription(`Users: **${s.users}**\nBlacklisted: **${s.blacklisted}**\nMinecraft: **${s.minecraftServers}**\nBot/Code: **${s.codeServers}**\nTotal: **${s.totalServers}**\nRunning: **${s.running}**\nSuspended: **${s.suspended}**`).setColor(0xe0002a)]});}
 if(i.commandName==='staff-manage-server'){const id=i.options.getString('server',true);return i.reply({content:`Staff controls for **${id}**`,components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`staffserver:${i.user.id}:${id}:start`).setLabel('Start').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`staffserver:${i.user.id}:${id}:stop`).setLabel('Stop').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`staffserver:${i.user.id}:${id}:suspend`).setLabel('Suspend').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId(`staffserver:${i.user.id}:${id}:delete`).setLabel('Delete').setStyle(ButtonStyle.Danger))]});}
 if(i.commandName==='staff-manage-user'){const target=i.options.getUser('user',true);const x=await api(`/internal/staff/user/${target.id}`,i.user.id);return i.reply({embeds:[new EmbedBuilder().setTitle('Staff User').setDescription(`User: **${x.user.username}**\nEmail: **${x.user.email||'none'}**\nCoins: **${x.user.coins}**\nServers: **${x.servers.length}**\nBlacklisted: **${x.user.blacklisted?'yes':'no'}**`).setColor(0xe0002a)]});}
 if(i.commandName==='staff-purge-servers'){const mode=i.options.getString('type',true);const x=await api('/internal/staff/purge',i.user.id,{method:'POST',body:JSON.stringify({mode,confirm:false})});return i.reply({content:`This action will delete **${x.count}** servers matching **${mode}**. Run the command again only after verifying the target set in the dashboard.`,ephemeral:true});}
 return i.reply({content:'Unsupported staff operation.',ephemeral:true});}

bot.on('messageCreate',async(m:Message)=>{if(m.author.bot||!m.content.startsWith('a!'))return;const [name,...args]=m.content.slice(2).trim().split(/\s+/);if(!name)return;try{if(name==='manage-server'||name==='my-account'){const fake:any={user:m.author,id:m.author.id,commandName:name,isChatInputCommand:()=>true,isRepliable:()=>true,reply:(x:any)=>m.reply(x),followUp:(x:any)=>m.reply(x),replied:false,deferred:false,options:{getUser:()=>null,getInteger:()=>null,getString:()=>null}};return staffOrUser(fake);}catch(e:any){await m.reply(e.message||'Operation failed');}});
async function staffOrUser(i:any){if(i.commandName==='manage-server'){const list=await api('/internal/servers',i.user.id);if(!list.length)return i.reply({content:'You do not have any servers.'});return i.reply({content:list.slice(0,20).map((s:any)=>`${s.name} • ${s.public_id}`).join('\n')});}const m=await api('/internal/me',i.user.id);return i.reply({content:`${m.user.username} • ${m.user.coins} ATX Coins • ${m.servers.length} servers`});}

bot.login(process.env.DISCORD_BOT_TOKEN);
