import {Client,GatewayIntentBits,REST,Routes,SlashCommandBuilder,ActionRowBuilder,StringSelectMenuBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,ChatInputCommandInteraction,Interaction,Message} from 'discord.js';
import crypto from 'node:crypto';
const API=(process.env.API_URL||'http://api:4000').replace(/\/$/,'');
const SECRET=process.env.ATXCLOUD_INTERNAL_SECRET||'';
const bot=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent]});
const commands=[
 new SlashCommandBuilder().setName('manage-server').setDescription('Manage your AtxCloud servers'),
 new SlashCommandBuilder().setName('my-account').setDescription('View your AtxCloud account'),
 new SlashCommandBuilder().setName('gift-coins').setDescription('Transfer coins').addUserOption(o=>o.setName('user').setDescription('Recipient').setRequired(true)).addIntegerOption(o=>o.setName('coins').setDescription('Amount').setRequired(true).setMinValue(1)),
 new SlashCommandBuilder().setName('share-access').setDescription('Share server access').addStringOption(o=>o.setName('server').setDescription('Server ID').setRequired(true)).addUserOption(o=>o.setName('user').setDescription('User').setRequired(true)),
 new SlashCommandBuilder().setName('remove-access').setDescription('Remove server access').addStringOption(o=>o.setName('server').setDescription('Server ID').setRequired(true)).addUserOption(o=>o.setName('user').setDescription('User').setRequired(true)),
 new SlashCommandBuilder().setName('staff-accounts').setDescription('Staff: list accounts'),new SlashCommandBuilder().setName('staff-servers').setDescription('Staff: list servers'),new SlashCommandBuilder().setName('staff-manage-user').setDescription('Staff: manage a user').addUserOption(o=>o.setName('user').setDescription('User').setRequired(true)),new SlashCommandBuilder().setName('staff-manage-server').setDescription('Staff: manage a server').addStringOption(o=>o.setName('server').setDescription('Server ID').setRequired(true)),new SlashCommandBuilder().setName('staff-stats').setDescription('Staff: system statistics'),new SlashCommandBuilder().setName('staff-purge-servers').setDescription('Staff: purge servers').addStringOption(o=>o.setName('type').setDescription('Selection').setRequired(true).addChoices({name:'Suspended',value:'suspended'},{name:'Offline',value:'offline'},{name:'Blacklisted',value:'blacklisted'}))
].map(x=>x.toJSON());
async function api(path:string,discordId:string,init:any={}){const r=await fetch(`${API}${path}`,{...init,headers:{'content-type':'application/json','x-atx-internal-secret':SECRET,'x-discord-user':discordId,...(init.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`API ${r.status}`);return d;}
const rid=()=>crypto.randomBytes(16).toString('hex');
function serverEmbed(s:any,r:any){const x=r?.current??r;return new EmbedBuilder().setTitle(s.name).setDescription(`Server ID: **${s.public_id}**\nSoftware: **${s.egg_name||s.egg_id}**\nVersion: **${s.version||'Not set'}**\nStatus: **${x?.state||'unknown'}**\nRAM: **${x?.memory_bytes?Math.round(x.memory_bytes/1048576):0} MB / 1024 MB**\nCPU: **${Math.round(x?.cpu_absolute||0)}% / 70%**\nSSD: **${x?.disk_bytes?(x.disk_bytes/1073741824).toFixed(2):0} GB / 5 GB**\nBackups: **${s.backups_used??0} / 3**`).setColor(0xe0002a);}
function powerRow(id:string,user:string){return new ActionRowBuilder<ButtonBuilder>().addComponents(...(['start','stop','restart','kill'] as const).map(a=>new ButtonBuilder().setCustomId(`power:${user}:${id}:${a}`).setLabel(a[0].toUpperCase()+a.slice(1)).setStyle(a==='kill'?ButtonStyle.Danger:a==='start'?ButtonStyle.Success:ButtonStyle.Secondary)));}
async function staffCheck(user:string){return (await api('/internal/staff/check',user)).staff;}
function expired(i:Interaction){return !!(i.isButton()||i.isStringSelectMenu())&&!!i.message&&Date.now()-i.message.createdTimestamp>120000;}
async function listForManage(user:string){const list=await api('/internal/servers',user);if(!list.length)return null;return new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId(`select:${user}`).setPlaceholder('Select a server').addOptions(list.slice(0,25).map((s:any)=>({label:String(s.name).slice(0,100),value:s.public_id,description:s.public_id}))));}

bot.once('ready',async()=>{const rest=new REST({version:'10'}).setToken(process.env.DISCORD_BOT_TOKEN!);await rest.put(Routes.applicationGuildCommands(bot.user!.id,process.env.DISCORD_GUILD_ID!),{body:commands});console.log(`AtxCloud bot ready as ${bot.user?.tag}`);});

bot.on('interactionCreate',async(i:Interaction)=>{try{
 if(expired(i))return i.update({content:'This interaction expired after 120 seconds. Run the command again.',components:[]}).catch(()=>{});
 if(i.isStringSelectMenu()&&i.customId.startsWith('select:')){const owner=i.customId.split(':')[1];if(i.user.id!==owner)return i.reply({content:'This control belongs to another user.',ephemeral:true});const x=await api(`/internal/servers/${i.values[0]}`,i.user.id);return i.update({content:'Live server controls',embeds:[serverEmbed(x.server,x.resource)],components:[powerRow(x.server.public_id,i.user.id)]});}
 if(i.isButton()){
  const p=i.customId.split(':');
  if(p[0]==='cancel'){if(i.user.id!==p[1])return i.reply({content:'Only the invoking user can cancel this action.',ephemeral:true});return i.update({content:'Action cancelled.',components:[]});}
  if(p[0]==='power'){if(i.user.id!==p[1])return i.reply({content:'This control panel belongs to another user.',ephemeral:true});await i.deferUpdate();await api(`/internal/servers/${p[2]}/power`,i.user.id,{method:'POST',body:JSON.stringify({signal:p[3]})});const fresh=await api(`/internal/servers/${p[2]}`,i.user.id);return i.editReply({embeds:[serverEmbed(fresh.server,fresh.resource)],components:[powerRow(p[2],i.user.id)]});}
  if(p[0]==='gift'){if(i.user.id!==p[1])return i.reply({content:'Only the invoking user can confirm this transfer.',ephemeral:true});await api('/internal/coins/gift',i.user.id,{method:'POST',body:JSON.stringify({targetDiscordId:p[2],coins:Number(p[3]),idempotencyKey:p[4]})});return i.update({content:`Transferred **${p[3]}** coins successfully.`,components:[]});}
  if(p[0]==='access'){if(i.user.id!==p[1])return i.reply({content:'Only the invoking user can confirm this action.',ephemeral:true});await api('/internal/access',i.user.id,{method:'POST',body:JSON.stringify({action:p[2],serverId:p[3],targetDiscordId:p[4]})});return i.update({content:`Access ${p[2]==='add'?'granted':'removed'} successfully.`,components:[]});}
  if(p[0]==='reset'){if(i.user.id!==p[1])return i.reply({content:'Only the account owner can reset this password.',ephemeral:true});await i.deferUpdate();await api('/internal/account/reset-password',i.user.id,{method:'POST'});return i.editReply({content:'Your new Pterodactyl password has been generated and sent to your Discord DMs.',components:[]});}
  if(p[0]==='staffserver'){if(i.user.id!==p[1])return i.reply({content:'Only the invoking staff member can use these controls.',ephemeral:true});if(!(await staffCheck(i.user.id)))return i.reply({content:'Staff access required.',ephemeral:true});if(p[3]==='delete')return i.reply({content:'Deletion requires a fresh destructive-action confirmation.',ephemeral:true});await api(`/internal/staff/server/${p[2]}/action`,i.user.id,{method:'POST',body:JSON.stringify({action:p[3]})});return i.update({content:`Staff action **${p[3]}** completed for **${p[2]}**.`,components:[]});}
 }
 if(!i.isChatInputCommand())return;const user=i.user.id;
 if(i.commandName==='manage-server'){const row=await listForManage(user);if(!row)return i.reply({content:'You do not have any servers.',ephemeral:true});return i.reply({content:'Select a server to manage.',components:[row]});}
 if(i.commandName==='my-account'){const m=await api('/internal/me',user);return i.reply({embeds:[new EmbedBuilder().setTitle('AtxCloud Account').setDescription(`User: **${m.user.username}**\nEmail: **${m.user.email||'Not available'}**\nCoins: **${m.user.coins}**\nServers: **${m.servers.length}**\nCreated: **${new Date(m.user.createdAt).toLocaleString()}**`).setColor(0xe0002a)],components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setLabel('Reset password').setCustomId(`reset:${user}`).setStyle(ButtonStyle.Danger),new ButtonBuilder().setLabel('Open dashboard').setStyle(ButtonStyle.Link).setURL(process.env.DASHBOARD_URL||'https://dash.atxcloud.ggff.net'))]});}
 if(i.commandName==='gift-coins'){const t=i.options.getUser('user',true),n=i.options.getInteger('coins',true);const k=rid();return i.reply({content:`Transfer **${n}** coins to ${t}?`,components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`gift:${user}:${t.id}:${n}:${k}`).setLabel('Confirm transfer').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId(`cancel:${user}:${k}`).setLabel('Cancel').setStyle(ButtonStyle.Secondary))]});}
 if(i.commandName==='share-access'||i.commandName==='remove-access'){const s=i.options.getString('server',true),t=i.options.getUser('user',true),a=i.commandName==='share-access'?'add':'remove',k=rid();return i.reply({content:`Confirm **${a}** access for ${t} on **${s}**?`,components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`access:${user}:${a}:${s}:${t.id}:${k}`).setLabel('Confirm').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId(`cancel:${user}:${k}`).setLabel('Cancel').setStyle(ButtonStyle.Secondary))]});}
 if(i.commandName.startsWith('staff-'))return staffCommand(i as ChatInputCommandInteraction);
 }catch(e:any){if(i.isRepliable())return i.replied||i.deferred?i.followUp({content:e.message||'Operation failed',ephemeral:true}):i.reply({content:e.message||'Operation failed',ephemeral:true});}}
});

bot.on('messageCreate',async(m:Message)=>{try{
 if(m.author.bot||!m.content.startsWith('a!'))return;
 const [raw,...args]=m.content.slice(2).trim().split(/\s+/);const cmd=String(raw||'').toLowerCase();if(!cmd)return;
 if(cmd==='manage-server'){const row=await listForManage(m.author.id);if(!row)return m.reply('You do not have any servers.');return m.reply({content:'Select a server to manage.',components:[row]});}
 if(cmd==='my-account'){const x=await api('/internal/me',m.author.id);return m.reply({embeds:[new EmbedBuilder().setTitle('AtxCloud Account').setDescription(`User: **${x.user.username}**\nEmail: **${x.user.email||'Not available'}**\nCoins: **${x.user.coins}**\nServers: **${x.servers.length}**\nCreated: **${new Date(x.user.createdAt).toLocaleString()}**`).setColor(0xe0002a)]});}
 if(cmd==='gift-coins'){const target=m.mentions.users.first(),amount=Number(args.find(x=>/^\d+$/.test(x))||0);if(!target||!Number.isSafeInteger(amount)||amount<=0)return m.reply('Usage: `a!gift-coins @user <coins>`');const k=rid();return m.reply({content:`Transfer **${amount}** coins to ${target}?`,components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`gift:${m.author.id}:${target.id}:${amount}:${k}`).setLabel('Confirm transfer').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId(`cancel:${m.author.id}:${k}`).setLabel('Cancel').setStyle(ButtonStyle.Secondary))]});}
 if(cmd==='share-access'||cmd==='remove-access'){const server=args.find(x=>!x.startsWith('<@'))||'',target=m.mentions.users.first(),a=cmd==='share-access'?'add':'remove';if(!server||!target)return m.reply(`Usage: \`a!${cmd} <server id> @user\``);const k=rid();return m.reply({content:`Confirm **${a}** access for ${target} on **${server}**?`,components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`access:${m.author.id}:${a}:${server}:${target.id}:${k}`).setLabel('Confirm').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId(`cancel:${m.author.id}:${k}`).setLabel('Cancel').setStyle(ButtonStyle.Secondary))]});}
 if(cmd==='staff-accounts'||cmd==='staff-servers'||cmd==='staff-stats'){if(!(await staffCheck(m.author.id)))return m.reply('Staff access required.');const path=cmd==='staff-accounts'?'/internal/staff/accounts':cmd==='staff-servers'?'/internal/staff/servers':'/internal/staff/stats';const x=await api(path,m.author.id);const text=cmd==='staff-accounts'?x.accounts.slice(0,25).map((u:any)=>`**${u.username}** • ${u.email||'no email'} • ${u.blacklisted?'blacklisted':'active'}`).join('\n'):cmd==='staff-servers'?x.servers.slice(0,25).map((s:any)=>`**${s.name}** • ${s.public_id} • ${s.owner}`).join('\n'):`Users: **${x.users}**\nBlacklisted: **${x.blacklisted}**\nMinecraft: **${x.minecraftServers}**\nBot/Code: **${x.codeServers}**\nTotal: **${x.totalServers}**\nRunning: **${x.running}**\nSuspended: **${x.suspended}**`;return m.reply({embeds:[new EmbedBuilder().setTitle(`AtxCloud ${cmd.replaceAll('-',' ')}`).setDescription(text||'No data').setColor(0xe0002a)]});}
 if(cmd==='staff-manage-server'){if(!(await staffCheck(m.author.id)))return m.reply('Staff access required.');const server=args[0];if(!server)return m.reply('Usage: `a!staff-manage-server <server id>`');return m.reply({content:`Staff controls for **${server}**`,components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`staffserver:${m.author.id}:${server}:start`).setLabel('Start').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`staffserver:${m.author.id}:${server}:stop`).setLabel('Stop').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`staffserver:${m.author.id}:${server}:suspend`).setLabel('Suspend').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId(`staffserver:${m.author.id}:${server}:delete`).setLabel('Delete').setStyle(ButtonStyle.Danger))]});}
 if(cmd==='staff-manage-user'){if(!(await staffCheck(m.author.id)))return m.reply('Staff access required.');const target=m.mentions.users.first();if(!target)return m.reply('Usage: `a!staff-manage-user @user`');const x=await api(`/internal/staff/user/${target.id}`,m.author.id);return m.reply({embeds:[new EmbedBuilder().setTitle('Staff User').setDescription(`User: **${x.user.username}**\nEmail: **${x.user.email||'none'}**\nCoins: **${x.user.coins}**\nServers: **${x.servers.length}**\nBlacklisted: **${x.user.blacklisted?'yes':'no'}**`).setColor(0xe0002a)]});}
 if(cmd==='staff-purge-servers'){if(!(await staffCheck(m.author.id)))return m.reply('Staff access required.');const mode=args[0];if(!['suspended','offline','blacklisted'].includes(mode))return m.reply('Usage: `a!staff-purge-servers suspended|offline|blacklisted`');const x=await api('/internal/staff/purge',m.author.id,{method:'POST',body:JSON.stringify({mode,confirm:false})});return m.reply(`Matched **${x.count}** servers for **${mode}**. Destructive purge requires a fresh confirmation in the staff dashboard.`);}
 }catch(e:any){return m.reply(e.message||'Operation failed').catch(()=>{});}});

async function staffCommand(i:ChatInputCommandInteraction){if(!(await staffCheck(i.user.id)))return i.reply({content:'Staff access required.',ephemeral:true});
 if(i.commandName==='staff-accounts'){const x=await api('/internal/staff/accounts',i.user.id);return i.reply({embeds:[new EmbedBuilder().setTitle('AtxCloud Accounts').setDescription(x.accounts.slice(0,25).map((u:any)=>`**${u.username}** • ${u.email||'no email'} • ${u.blacklisted?'blacklisted':'active'}`).join('\n')||'No accounts').setColor(0xe0002a)]});}
 if(i.commandName==='staff-servers'){const x=await api('/internal/staff/servers',i.user.id);return i.reply({embeds:[new EmbedBuilder().setTitle('AtxCloud Servers').setDescription(x.servers.slice(0,25).map((s:any)=>`**${s.name}** • ${s.public_id} • ${s.owner}`).join('\n')||'No servers').setColor(0xe0002a)]});}
 if(i.commandName==='staff-stats'){const s=await api('/internal/staff/stats',i.user.id);return i.reply({embeds:[new EmbedBuilder().setTitle('AtxCloud Staff Stats').setDescription(`Users: **${s.users}**\nBlacklisted: **${s.blacklisted}**\nMinecraft: **${s.minecraftServers}**\nBot/Code: **${s.codeServers}**\nTotal servers: **${s.totalServers}**\nRunning: **${s.running}**\nSuspended: **${s.suspended}`).setColor(0xe0002a)]});}
 if(i.commandName==='staff-manage-server'){const s=i.options.getString('server',true);return i.reply({content:`Staff controls for **${s}**`,components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`staffserver:${i.user.id}:${s}:start`).setLabel('Start').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`staffserver:${i.user.id}:${s}:stop`).setLabel('Stop').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`staffserver:${i.user.id}:${s}:suspend`).setLabel('Suspend').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId(`staffserver:${i.user.id}:${s}:delete`).setLabel('Delete').setStyle(ButtonStyle.Danger))]});}
 if(i.commandName==='staff-manage-user'){const t=i.options.getUser('user',true),x=await api(`/internal/staff/user/${t.id}`,i.user.id);return i.reply({embeds:[new EmbedBuilder().setTitle('Staff User').setDescription(`User: **${x.user.username}**\nEmail: **${x.user.email||'none'}**\nCoins: **${x.user.coins}**\nServers: **${x.servers.length}**\nBlacklisted: **${x.user.blacklisted?'yes':'no'}**`).setColor(0xe0002a)]});}
 if(i.commandName==='staff-purge-servers'){const mode=i.options.getString('type',true),x=await api('/internal/staff/purge',i.user.id,{method:'POST',body:JSON.stringify({mode,confirm:false})});return i.reply({content:`Matched **${x.count}** servers for **${mode}**. Final deletion must be confirmed from the staff dashboard.`,ephemeral:true});}
 return i.reply({content:'Unsupported staff operation.',ephemeral:true});}

bot.login(process.env.DISCORD_BOT_TOKEN);